#! /usr/bin/python
# -*- coding:utf-8
import sys
import pancito

conn = pancito.opendb()
c = conn.cursor()
contractId = int(sys.argv[1])
userId = int(sys.argv[2])
c.execute("SELECT * FROM adhesionorder WHERE contract_id = ? AND user_id = ?", (contractId, userId))
orders = c.fetchall()
db = pancito.db.DBManager(conn)
for bake in db.getBakes(contractId):
    #db.deleteBakeOrders(userId, bake['rowid'])
    for order in orders:
        print "Adding bake order: date %s product %s quantity %s" % (bake['bakedate'], order['productid'], order['quantity'])
        db.addBakeOrder(userId, bake['rowid'], order['productid'], order['quantity'])
c.execute("INSERT INTO adhesion (contract_id, user_id) VALUES (?, ?)", (contractId, userId))
conn.commit()
