#! /usr/bin/python
import os.path
import pancito

def writeMail(user):
    with open(os.path.join(pancito.datadir, "mail", str(user['rowid'])), "w") as f:
        content = mailTemplate % {'url': 'http://m.pancito.fr/order?userId=%s&t=%s' % (user['rowid'], pancito.genToken(user)), 'email': user['email']}
        f.write(content.encode('utf-8'))

with open(os.path.join(pancito.datadir, "mail.tmpl")) as f:
    mailTemplate = f.read().decode('utf-8')

conn = pancito.opendb()
c = conn.cursor()
c.execute("SELECT rowid, * FROM user")
for user in c.fetchall():
    writeMail(user)
