#! /usr/bin/python
import os.path
import pancito
import Cheetah.Template
import email.header

def encodeHeader(v):
    return email.header.Header(v, 'utf-8').encode()

def writeMail(user):
    with open(os.path.join(pancito.datadir, "mail", "%02u" % user['rowid']), "w") as f:
        t = Cheetah.Template.Template(file=os.path.join(pancito.datadir, "mail.tmpl"))
        t.url = 'http://m.pancito.fr/order?userId=%s&t=%s' % (user['rowid'], pancito.genToken(user))
        t.email = user['email']
        t.encodeHeader = encodeHeader
        content = unicode(t)
        f.write(content.encode('utf-8'))

conn = pancito.opendb()
c = conn.cursor()
c.execute("SELECT rowid, * FROM user")
for user in c.fetchall():
    writeMail(user)
