#! /usr/bin/python
import os.path
import pancito.mail

template = os.path.join(pancito.datadir, "mail.tmpl")
conn = pancito.opendb()
c = conn.cursor()
c.execute("SELECT * FROM user WHERE ismailing")
for user in c.fetchall():
    pancito.mail.writeMail(user, pancito.mail.mail_template(user, template))
