#! /usr/bin/python
import os.path
import pancito
import pancito.mail
import sys

template = "data/reminder.tmpl"
conn = pancito.opendb()
c = conn.cursor()
c.execute("SELECT * FROM user WHERE ismailing AND id NOT IN (SELECT userid FROM bakeorder WHERE bakeid = ?)", (int(sys.argv[1]),))
for user in c.fetchall():
    pancito.mail.writeMail(user, pancito.mail.mail_template(user, template))
