#! /usr/bin/python
# coding=utf-8
import os.path
import pancito.mail
import sys
import Cheetah.Template

contractId = int(sys.argv[1])
userId = int(sys.argv[2])
pdfFile = sys.argv[3]
conn = pancito.opendb()
c = conn.cursor()
c.execute("SELECT * FROM contract WHERE id = ?", (contractId,))
db = pancito.db.DBManager(conn)
contract = db.toDisplayContract(c.fetchone())
for field in ('startdate', 'enddate'):
    contract[field] = contract[field].strftime("%d %B %Y")
c.execute("SELECT * FROM user WHERE id = ?", (userId,))
user = c.fetchone()
with open(pdfFile) as f:
    pdfData = f.read()
pancito.mail.sendContract(user, contract, pdfData)
