#! /usr/bin/python
import os.path, sys
sys.path.append(os.path.dirname(os.path.dirname(__file__)))
import pancito.mail
import sys
import Cheetah.Template

template = sys.argv[1]
contractId = int(sys.argv[2])
conn = pancito.opendb()
db = pancito.db.DBManager(conn)
contract = db.getContract(contractId)
for field in ('startdate', 'enddate'):
    contract[field] = contract[field].strftime("%d %B %Y")
c = conn.cursor()
c.execute("SELECT * FROM user WHERE ismailing and NOT ismember")
for user in c.fetchall():
    t = Cheetah.Template.Template(file=template)
    t.registrationUrl = "http://m.pancito.fr/register?u=%s&c=%s&t=%s" % (user['id'], contractId, pancito.genToken(user, contractId))
    t.contract = contract
    pancito.mail.writeMail(user, pancito.mail.mail_template(user, t))
